apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "game-service.fullname" . }}
  labels:
    {{- include "game-service.labels" . | nindent 4 }}
{{- if .Values.imagePullSecrets }}
imagePullSecrets:
{{- toYaml .Values.imagePullSecrets | nindent 2 }}
{{- end }}