image:
  repository: ghcr.io/rubhern/videogame-platform/game-service
  pullPolicy: IfNotPresent
  digest: "sha256-e110bb60a3251b6736fb997cb88fa0b5611d30d96ede54363e18486bc877d3b9.sig"
  tag: ""

replicaCount: 1

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

ingress:
  enabled: true
  className: nginx
  host: game.local
  path: /
  tls: false

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 256Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80

livenessProbe:
  enabled: true
  path: /actuator/health/liveness
  initialDelaySeconds: 30
  periodSeconds: 10

readinessProbe:
  enabled: true
  path: /actuator/health/readiness
  initialDelaySeconds: 30
  periodSeconds: 10

serviceAccount:
  create: true
  name: ""

imagePullSecrets:
  - name: ghcr-pull-secret

podAnnotations: {}
podLabels: {}