environment: dev

image:
  repository: ghcr.io/rubhern/videogame-platform/game-service
  pullPolicy: IfNotPresent
  digest: "sha256:dd5eacc61016f74c0deab2bd30a36c52d4ac3b43c983cf4a3b4aafbe2a3a10d5"
  tag: ""

replicaCount: 1

service:
  type: ClusterIP
  port: 80
  targetPort: 8090

ingress:
  enabled: true
  className: kong
  host: game.local
  path: /
  tls: false

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 256Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80

livenessProbe:
  enabled: true
  path: /actuator/health/liveness
  initialDelaySeconds: 30
  periodSeconds: 10

readinessProbe:
  enabled: true
  path: /actuator/health/readiness
  initialDelaySeconds: 30
  periodSeconds: 10

serviceAccount:
  create: true
  name: ""

imagePullSecrets:
  - name: ghcr-pull-secret

podAnnotations: {}
podLabels: {}