environment: dev

config:
  database:
    url: "jdbc:postgresql://postgres.postgres.svc.cluster.local:5432/gamedb"
    username: "rubhern"
    password:
      secretName: "game-service-db-creds"
      secretKey: "password"

  jpa:
    showSql: "true"
  info:
    environment: "development"

image:
  repository: ghcr.io/rubhern/videogame-platform/game-service
  pullPolicy: IfNotPresent
  digest: "sha256:657a7b069fc9618a3803815264648ced86107efa9e6d31169d19dc135f17d896"
  tag: ""

replicaCount: 1

service:
  type: ClusterIP
  port: 80
  targetPort: 8090

ingress:
  enabled: true
  className: kong
  host: game.local
  path: /
  tls: false

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 256Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80

livenessProbe:
  enabled: true
  path: /actuator/health/liveness
  initialDelaySeconds: 30
  periodSeconds: 10

readinessProbe:
  enabled: true
  path: /actuator/health/readiness
  initialDelaySeconds: 30
  periodSeconds: 10

serviceAccount:
  create: true
  name: ""

imagePullSecrets:
  - name: ghcr-pull-secret

podAnnotations: {}
podLabels: {}