#!/usr/bin/env bash

set -Eeuo pipefail

repository_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
env_file="$repository_root/.env"
compose_file="$repository_root/compose.yaml"

readonly postgres_image="postgres:18.4-bookworm"
readonly keycloak_image="quay.io/keycloak/keycloak:26.7.0"
readonly expected_project_name="videogame-platform"

usage() {
  cat <<'EOF'
Usage: bash scripts/local-dependencies.sh <command>

Commands:
  up             Create .env when absent, then start PostgreSQL and Keycloak.
  down           Stop containers without deleting local data.
  status         Show container and health status.
  logs           Follow PostgreSQL and Keycloak logs.
  verify         Verify versions, health, role isolation, realm, confidential PKCE client and local user.
  verify-images  Verify linux/amd64 and linux/arm64 in both image manifests.
  reset [--yes]  Delete only this Compose project's disposable containers and volumes.
EOF
}

die() {
  printf 'ERROR: %s\n' "$*" >&2
  exit 1
}

require_command() {
  command -v "$1" >/dev/null 2>&1 || die "Required command not found: $1"
}

random_secret() {
  od -An -N32 -tx1 /dev/urandom | tr -d ' \n'
}

create_env_if_missing() {
  if [[ -f "$env_file" ]]; then
    return
  fi

  umask 077
  {
    printf '# Generated by scripts/local-dependencies.sh. Never commit this file.\n'
    printf 'COMPOSE_PROJECT_NAME=videogame-platform\n'
    printf 'POSTGRES_PORT=5432\n'
    printf 'POSTGRES_ADMIN_PASSWORD=%s\n' "$(random_secret)"
    printf 'APPLICATION_DB_PASSWORD=%s\n' "$(random_secret)"
    printf 'APPLICATION_MIGRATION_DB_PASSWORD=%s\n' "$(random_secret)"
    printf 'KEYCLOAK_DB_PASSWORD=%s\n' "$(random_secret)"
    printf 'KEYCLOAK_HTTP_PORT=8180\n'
    printf 'KEYCLOAK_MANAGEMENT_PORT=9000\n'
    printf 'KEYCLOAK_HOSTNAME=http://localhost:8180\n'
    printf 'KEYCLOAK_ADMIN_USERNAME=local-admin\n'
    printf 'KEYCLOAK_ADMIN_PASSWORD=%s\n' "$(random_secret)"
    printf 'KEYCLOAK_BFF_CLIENT_SECRET=%s\n' "$(random_secret)"
    printf 'LOCAL_TEST_USER_USERNAME=local-user\n'
    printf 'LOCAL_TEST_USER_PASSWORD=%s\n' "$(random_secret)"
  } >"$env_file"

  printf 'Created ignored local configuration at %s with generated credentials.\n' "$env_file"
}

secure_env_file() {
  chmod 600 "$env_file"
}

require_env() {
  [[ -f "$env_file" ]] || die ".env does not exist; run the up command first"

  local variable
  local required_variables=(
    COMPOSE_PROJECT_NAME
    POSTGRES_ADMIN_PASSWORD
    APPLICATION_DB_PASSWORD
    APPLICATION_MIGRATION_DB_PASSWORD
    KEYCLOAK_DB_PASSWORD
    KEYCLOAK_HOSTNAME
    KEYCLOAK_ADMIN_USERNAME
    KEYCLOAK_ADMIN_PASSWORD
    KEYCLOAK_BFF_CLIENT_SECRET
    LOCAL_TEST_USER_USERNAME
    LOCAL_TEST_USER_PASSWORD
  )

  for variable in "${required_variables[@]}"; do
    grep -Eq "^${variable}=.+$" "$env_file" || die "Set ${variable} in .env"
  done

  if grep -Eq '=(GENERATE_ME|CHANGE_ME|replace-me)$' "$env_file"; then
    die ".env still contains placeholder credentials"
  fi

  if [[ "$(env_value COMPOSE_PROJECT_NAME)" != "$expected_project_name" ]]; then
    die "COMPOSE_PROJECT_NAME must remain ${expected_project_name} so lifecycle commands cannot target another Compose project"
  fi

  secure_env_file
}

env_value() {
  local variable="$1"
  sed -n "s/^${variable}=//p" "$env_file" | tail -n 1
}

compose() {
  docker compose --env-file "$env_file" --file "$compose_file" "$@"
}

ensure_compose_available() {
  require_command docker
  docker compose version >/dev/null 2>&1 || die "Docker Compose is not available"
  docker info >/dev/null 2>&1 || die "The Docker daemon is not reachable"
}

verify_image_platform() {
  local image="$1"
  local manifest

  manifest="$(docker buildx imagetools inspect "$image")" || die "Could not inspect $image"
  grep -q 'linux/amd64' <<<"$manifest" || die "$image has no linux/amd64 manifest"
  grep -q 'linux/arm64' <<<"$manifest" || die "$image has no linux/arm64 manifest"
  printf 'Verified %s: linux/amd64 and linux/arm64.\n' "$image"
}

verify_runtime() {
  local keycloak_hostname
  local authorization_status
  local database_result
  local identity_result
  local keycloak_version
  local postgres_version

  compose ps --status running
  compose exec -T postgres pg_isready --username=postgres --dbname=postgres >/dev/null
  compose exec -T postgres bash -ec \
    'PGPASSWORD="$APPLICATION_DB_PASSWORD" psql --host=127.0.0.1 --username=videogame_app --dbname=videogame_platform --command="SELECT 1" >/dev/null'
  compose exec -T postgres bash -ec \
    'PGPASSWORD="$APPLICATION_MIGRATION_DB_PASSWORD" psql --host=127.0.0.1 --username=videogame_app_migrator --dbname=videogame_platform --command="SELECT 1" >/dev/null'

  postgres_version="$(compose exec -T postgres psql --username=postgres --dbname=postgres --tuples-only --no-align --command='SHOW server_version;')"
  [[ "$postgres_version" == 18.* ]] || die "Expected PostgreSQL 18.x, found $postgres_version"

  keycloak_version="$(compose exec -T keycloak /opt/keycloak/bin/kc.sh --version)"
  [[ "$keycloak_version" == *"26.7."* ]] || die "Expected Keycloak 26.7.x, found $keycloak_version"

  database_result="$(compose exec -T postgres psql --username=postgres --dbname=postgres --tuples-only --no-align --command="
    SELECT concat_ws(':',
      has_database_privilege('videogame_app', 'videogame_platform', 'CONNECT'),
      has_database_privilege('videogame_app', 'videogame_keycloak', 'CONNECT'),
      has_database_privilege('videogame_app_migrator', 'videogame_platform', 'CONNECT'),
      has_database_privilege('videogame_app_migrator', 'videogame_keycloak', 'CONNECT'),
      has_database_privilege('videogame_keycloak', 'videogame_keycloak', 'CONNECT'),
      has_database_privilege('videogame_keycloak', 'videogame_platform', 'CONNECT'),
      (SELECT NOT rolsuper AND NOT rolcreatedb AND NOT rolcreaterole FROM pg_roles WHERE rolname = 'videogame_app'),
      (SELECT NOT rolsuper AND NOT rolcreatedb AND NOT rolcreaterole FROM pg_roles WHERE rolname = 'videogame_app_migrator'),
      (SELECT NOT rolsuper AND NOT rolcreatedb AND NOT rolcreaterole FROM pg_roles WHERE rolname = 'videogame_keycloak'),
      NOT has_schema_privilege('videogame_app', 'public', 'CREATE'),
      (SELECT pg_get_userbyid(datdba) = 'videogame_app_migrator' FROM pg_database WHERE datname = 'videogame_platform'),
      (SELECT pg_get_userbyid(datdba) = 'videogame_keycloak' FROM pg_database WHERE datname = 'videogame_keycloak')
    );
  ")"
  [[ "$database_result" == "t:f:t:f:t:f:t:t:t:t:t:t" ]] \
    || die "Database role isolation or ownership check failed: $database_result"

  keycloak_hostname="$(env_value KEYCLOAK_HOSTNAME)"
  require_command curl
  curl --fail --silent --show-error \
    "$keycloak_hostname/realms/videogame-platform/.well-known/openid-configuration" \
    >/dev/null

  authorization_status="$(curl --silent --output /dev/null --write-out '%{http_code}' \
    --get "$keycloak_hostname/realms/videogame-platform/protocol/openid-connect/auth" \
    --data-urlencode 'client_id=videogame-platform-bff' \
    --data-urlencode 'redirect_uri=http://localhost:8080/login/oauth2/code/keycloak' \
    --data-urlencode 'response_type=code' \
    --data-urlencode 'scope=openid' \
    --data-urlencode 'code_challenge=0123456789012345678901234567890123456789012' \
    --data-urlencode 'code_challenge_method=S256')"
  [[ "$authorization_status" == "200" || "$authorization_status" == "302" ]] \
    || die "The imported BFF client rejected a valid authorization request (HTTP $authorization_status)"

  identity_result="$(compose exec -T postgres psql --username=postgres --dbname=videogame_keycloak \
    --tuples-only --no-align --command="
      SELECT concat_ws(':',
        (SELECT count(*) = 1 FROM realm WHERE name = 'videogame-platform'),
        (SELECT count(*) = 1
           FROM client c
           JOIN realm r ON r.id = c.realm_id
          WHERE r.name = 'videogame-platform'
            AND c.client_id = 'videogame-platform-bff'
            AND c.enabled
            AND NOT c.public_client
            AND c.client_authenticator_type = 'client-secret'
            AND c.standard_flow_enabled
            AND NOT c.implicit_flow_enabled
            AND NOT c.direct_access_grants_enabled
            AND NOT c.service_accounts_enabled
            AND c.secret IS NOT NULL),
        (SELECT count(*) = 1
           FROM client_attributes ca
           JOIN client c ON c.id = ca.client_id
           JOIN realm r ON r.id = c.realm_id
          WHERE r.name = 'videogame-platform'
            AND c.client_id = 'videogame-platform-bff'
            AND ca.name = 'pkce.code.challenge.method'
            AND ca.value = 'S256'),
        (SELECT count(*) = 1
           FROM user_entity u
           JOIN realm r ON r.id = u.realm_id
          WHERE r.name = 'videogame-platform'),
        (SELECT count(*) = 1
           FROM credential cr
           JOIN user_entity u ON u.id = cr.user_id
           JOIN realm r ON r.id = u.realm_id
          WHERE r.name = 'videogame-platform'
            AND cr.type = 'password')
      );
    ")"
  [[ "$identity_result" == "t:t:t:t:t" ]] \
    || die "Realm, confidential client, PKCE or local-user verification failed: $identity_result"

  printf 'Runtime verification passed: PostgreSQL %s, Keycloak 26.7.x, health, database isolation, realm, confidential PKCE client and local user.\n' "$postgres_version"
}

command_name="${1:-}"

case "$command_name" in
  up)
    ensure_compose_available
    create_env_if_missing
    require_env
    compose config --quiet
    compose up --detach --wait
    printf 'PostgreSQL is available on 127.0.0.1:%s.\n' "$(env_value POSTGRES_PORT)"
    printf 'Keycloak is available at %s.\n' "$(env_value KEYCLOAK_HOSTNAME)"
    ;;
  down)
    ensure_compose_available
    require_env
    compose down --remove-orphans
    ;;
  status)
    ensure_compose_available
    require_env
    compose ps
    ;;
  logs)
    ensure_compose_available
    require_env
    compose logs --follow postgres keycloak
    ;;
  verify)
    ensure_compose_available
    require_env
    verify_runtime
    ;;
  verify-images)
    ensure_compose_available
    docker buildx version >/dev/null 2>&1 || die "Docker Buildx is required to inspect OCI manifests"
    verify_image_platform "$postgres_image"
    verify_image_platform "$keycloak_image"
    ;;
  reset)
    ensure_compose_available
    require_env
    if [[ "${2:-}" != "--yes" ]]; then
      printf 'This deletes only containers and named volumes in Compose project %s.\n' "$(env_value COMPOSE_PROJECT_NAME)"
      read -r -p 'Delete disposable local PostgreSQL and Keycloak data? [y/N] ' confirmation
      [[ "$confirmation" == "y" || "$confirmation" == "Y" ]] || die "Reset cancelled"
    fi
    compose down --volumes --remove-orphans
    printf 'Deleted disposable Compose data. The ignored .env file was preserved.\n'
    ;;
  *)
    usage
    [[ -n "$command_name" ]] && exit 1
    ;;
esac
