#!/usr/bin/env bash

set -Eeuo pipefail

repository_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
env_file="$repository_root/.env"
backend_env_file="$repository_root/backend/.env"
compose_file="$repository_root/compose.yaml"
metrics_compose_file="$repository_root/compose.observability.yaml"
localization_compose_file="$repository_root/compose.localization.yaml"
with_observability=false
with_localization=false
reset_confirmed=false
recreate_observability=false
source "$repository_root/scripts/backend-artifact.sh"

readonly postgres_image="postgres:18.4-bookworm"
readonly keycloak_image="quay.io/keycloak/keycloak:26.7.0"
readonly expected_project_name="videogame-platform"

usage() {
  cat <<'EOF'
Usage: bash scripts/local-dependencies.sh <command> [options]

Commands:
  up             Create the ignored infrastructure/backend env files when absent,
                 then start PostgreSQL and Keycloak.
  application    Build and run the complete packaged application topology.
  observability  Start only Collector, Prometheus, Grafana, Alloy and Loki.
  verify-observability  Check provisioning, authentication and metrics queries.
  localization   Build and start only the optional catalogue translation helper.
  verify-localization  Check the loaded model/helper readiness.

  down           Stop containers without deleting local data.
  status         Show container and health status.
  logs           Follow PostgreSQL and Keycloak logs.
  verify         Verify versions, health, role isolation, realm, confidential PKCE client and local user.
  verify-images  Verify linux/amd64 and linux/arm64 in both image manifests.
  reset [--yes]  Delete only this Compose project's disposable containers and volumes.

Add --observability to up or application to include the metrics and logs stack.
Add --localization to up or application to include catalogue translation.
Add --recreate to observability to repair stale Docker Desktop bind mounts, preserving data.
Both flags can be combined. Install the pinned model using backend/README.md first.
Grafana: http://127.0.0.1:3000 (owner; .local-secrets/grafana-admin-password).
EOF
}

die() {
  printf 'ERROR: %s\n' "$*" >&2
  exit 1
}

require_command() {
  command -v "$1" >/dev/null 2>&1 || die "Required command not found: $1"
}

random_secret() {
  od -An -N32 -tx1 /dev/urandom | tr -d ' \n'
}

create_env_if_missing() {
  if [[ -f "$env_file" ]]; then
    return
  fi

  umask 077
  {
    printf '# Generated by scripts/local-dependencies.sh. Never commit this file.\n'
    printf 'COMPOSE_PROJECT_NAME=videogame-platform\n'
    printf 'POSTGRES_PORT=5432\n'
    printf 'POSTGRES_ADMIN_PASSWORD=%s\n' "$(random_secret)"
    printf 'APPLICATION_DB_PASSWORD=%s\n' "$(random_secret)"
    printf 'APPLICATION_MIGRATION_DB_PASSWORD=%s\n' "$(random_secret)"
    printf 'KEYCLOAK_DB_PASSWORD=%s\n' "$(random_secret)"
    printf 'KEYCLOAK_HTTP_PORT=8180\n'
    printf 'KEYCLOAK_MANAGEMENT_PORT=9000\n'
    printf 'KEYCLOAK_HOSTNAME=http://localhost:8180\n'
    printf 'KEYCLOAK_ADMIN_USERNAME=local-admin\n'
    printf 'KEYCLOAK_ADMIN_PASSWORD=%s\n' "$(random_secret)"
    printf 'KEYCLOAK_BFF_CLIENT_SECRET=%s\n' "$(random_secret)"
    printf 'LOCAL_TEST_USER_USERNAME=local-user\n'
    printf 'LOCAL_TEST_USER_PASSWORD=%s\n' "$(random_secret)"
    printf 'CATALOGUE_TRANSLATION_MODEL_DIR=.local-secrets/catalogue-models/tcbig-initial\n'
  } >"$env_file"

  printf 'Created ignored local configuration at %s with generated credentials.\n' "$env_file"
}

secure_env_file() {
  chmod 600 "$env_file"
}

require_env() {
  [[ -f "$env_file" ]] || die ".env does not exist; run the up command first"

  local variable
  local required_variables=(
    COMPOSE_PROJECT_NAME
    POSTGRES_ADMIN_PASSWORD
    APPLICATION_DB_PASSWORD
    APPLICATION_MIGRATION_DB_PASSWORD
    KEYCLOAK_DB_PASSWORD
    KEYCLOAK_HOSTNAME
    KEYCLOAK_ADMIN_USERNAME
    KEYCLOAK_ADMIN_PASSWORD
    KEYCLOAK_BFF_CLIENT_SECRET
    LOCAL_TEST_USER_USERNAME
    LOCAL_TEST_USER_PASSWORD
  )

  for variable in "${required_variables[@]}"; do
    grep -Eq "^${variable}=.+$" "$env_file" || die "Set ${variable} in .env"
  done

  if grep -Eq '=(GENERATE_ME|CHANGE_ME|replace-me)$' "$env_file"; then
    die ".env still contains placeholder credentials"
  fi

  if [[ "$(env_value COMPOSE_PROJECT_NAME)" != "$expected_project_name" ]]; then
    die "COMPOSE_PROJECT_NAME must remain ${expected_project_name} so lifecycle commands cannot target another Compose project"
  fi

  secure_env_file
}

env_value() {
  local variable="$1"
  sed -n "s/^${variable}=//p" "$env_file" | tail -n 1
}

create_backend_env_if_missing() {
  if [[ -f "$backend_env_file" ]]; then
    chmod 600 "$backend_env_file"
    return
  fi

  umask 077
  {
    printf '# Generated by scripts/local-dependencies.sh. Never commit this file.\n'
    printf 'SPRING_PROFILES_ACTIVE=\n'
    printf 'SERVER_PORT=8080\n'
    printf 'MANAGEMENT_SERVER_ADDRESS=127.0.0.1\n'
    printf 'MANAGEMENT_SERVER_PORT=8081\n'
    printf 'LOGGING_LEVEL_COM_VIDEOGAMEPLATFORM=INFO\n'
    printf 'APPLICATION_DB_URL=jdbc:postgresql://localhost:5432/videogame_platform\n'
    printf 'APPLICATION_DB_USERNAME=videogame_app\n'
    printf 'APPLICATION_DB_PASSWORD=%s\n' "$(env_value APPLICATION_DB_PASSWORD)"
    printf 'APPLICATION_DB_CONNECTION_TIMEOUT=3000\n'
    printf 'APPLICATION_DB_VALIDATION_TIMEOUT=1000\n'
    printf 'APPLICATION_DB_MAXIMUM_POOL_SIZE=10\n'
    printf 'APPLICATION_CATALOGUE_READINESS_TIMEOUT=2s\n'
    printf 'APPLICATION_FLYWAY_ENABLED=false\n'
    printf 'APPLICATION_MIGRATION_DB_URL=jdbc:postgresql://localhost:5432/videogame_platform\n'
    printf 'APPLICATION_MIGRATION_DB_USERNAME=videogame_app_migrator\n'
    printf 'APPLICATION_MIGRATION_DB_PASSWORD=%s\n' "$(env_value APPLICATION_MIGRATION_DB_PASSWORD)"
    printf 'SPRING_FLYWAY_LOCATIONS=classpath:db/migration\n'
    printf 'KEYCLOAK_BFF_CLIENT_SECRET=%s\n' "$(env_value KEYCLOAK_BFF_CLIENT_SECRET)"
    printf 'OIDC_ISSUER_URI=http://localhost:8180/realms/videogame-platform\n'
    printf 'APPLICATION_SESSION_TIMEOUT=30m\n'
    printf 'APPLICATION_SESSION_COOKIE_NAME=vgp_session\n'
    printf 'APPLICATION_SESSION_COOKIE_SECURE=false\n'
    printf 'CATALOGUE_JDBC_READ_TIMEOUT=5s\n'
    printf 'CATALOGUE_RELEASES_FRESHNESS_THRESHOLD=P7D\n'
    printf 'CATALOGUE_RELEASES_CACHE_CONTROL="public, max-age=60, stale-while-revalidate=300"\n'
    printf 'RATINGS_JDBC_OPERATION_TIMEOUT=5s\n'
    printf 'CATALOGUE_TRANSLATION_ENDPOINT=http://127.0.0.1:8092/translate\n'
    printf 'CATALOGUE_TRANSLATION_TIMEOUT=30s\n'
    printf 'TELEMETRY_OTLP_TRACES_ENABLED=false\n'
    printf 'TELEMETRY_OTLP_TRACES_ENDPOINT=http://localhost:4318/v1/traces\n'
    printf 'TELEMETRY_OTLP_METRICS_ENABLED=false\n'
    printf 'TELEMETRY_OTLP_METRICS_ENDPOINT=http://localhost:4318/v1/metrics\n'
    printf 'TELEMETRY_OTLP_METRICS_STEP=60s\n'
    printf 'TELEMETRY_TRACING_SAMPLING_PROBABILITY=1.0\n'
  } >"$backend_env_file"

  printf 'Created ignored backend configuration at %s with shared generated credentials.\n' "$backend_env_file"
}

prepare_local_metrics_secret() {
  local directory="$repository_root/.local-secrets"
  [[ ! -L "$directory" ]] || die "Refusing a symlink for local metrics credentials"
  mkdir -p "$directory"
  chmod 700 "$directory"
  local secret
  for name in grafana-admin-password grafana-database-password; do
    secret="$directory/$name"
    [[ ! -L "$secret" ]] || die "Refusing a symlink for local metrics credentials"
    if [[ ! -s "$secret" ]]; then (umask 077; random_secret >"$secret"); fi
    chmod 644 "$secret"
  done
}

local_model_directory() {
  local directory="${CATALOGUE_TRANSLATION_MODEL_DIR:-$(env_value CATALOGUE_TRANSLATION_MODEL_DIR)}"
  directory="${directory:-.local-secrets/catalogue-models/tcbig-initial}"
  [[ "$directory" == /* ]] || directory="$repository_root/$directory"
  printf '%s\n' "$directory"
}

require_local_model() {
  local directory
  directory="$(local_model_directory)"
  [[ -f "$directory/manifest.json" && -f "$directory/revision.txt" ]] \
    || die "Install the pinned catalogue model using backend/README.md, then set CATALOGUE_TRANSLATION_MODEL_DIR to its immutable directory"
}

compose() {
  local application_version
  application_version="$(backend_reactor_version)" \
    || die "Could not read the reactor version from pom.xml"

  local files=(--file "$compose_file")
  if [[ "$with_observability" == true ]]; then
    files+=(--file "$metrics_compose_file" --profile observability)
  fi
  if [[ "$with_localization" == true ]]; then
    files+=(--file "$localization_compose_file" --profile localization)
  fi
  APPLICATION_VERSION="$application_version" \
    CATALOGUE_TRANSLATION_MODEL_DIR="$(local_model_directory)" \
    docker compose --env-file "$env_file" "${files[@]}" "$@"
}

ensure_compose_available() {
  require_command docker
  require_command python3
  docker compose version >/dev/null 2>&1 || die "Docker Compose is not available"
  docker info >/dev/null 2>&1 || die "The Docker daemon is not reachable"
}

verify_image_platform() {
  local image="$1"
  local manifest

  manifest="$(docker buildx imagetools inspect "$image")" || die "Could not inspect $image"
  grep -q 'linux/amd64' <<<"$manifest" || die "$image has no linux/amd64 manifest"
  grep -q 'linux/arm64' <<<"$manifest" || die "$image has no linux/arm64 manifest"
  printf 'Verified %s: linux/amd64 and linux/arm64.\n' "$image"
}

verify_runtime() {
  local keycloak_hostname
  local authorization_status
  local database_result
  local identity_result
  local keycloak_version
  local postgres_version

  compose ps --status running
  compose exec -T postgres pg_isready --username=postgres --dbname=postgres >/dev/null
  compose exec -T postgres bash -ec \
    'PGPASSWORD="$APPLICATION_DB_PASSWORD" psql --host=127.0.0.1 --username=videogame_app --dbname=videogame_platform --command="SELECT 1" >/dev/null'
  compose exec -T postgres bash -ec \
    'PGPASSWORD="$APPLICATION_MIGRATION_DB_PASSWORD" psql --host=127.0.0.1 --username=videogame_app_migrator --dbname=videogame_platform --command="SELECT 1" >/dev/null'

  postgres_version="$(compose exec -T postgres psql --username=postgres --dbname=postgres --tuples-only --no-align --command='SHOW server_version;')"
  [[ "$postgres_version" == 18.* ]] || die "Expected PostgreSQL 18.x, found $postgres_version"

  keycloak_version="$(compose exec -T keycloak /opt/keycloak/bin/kc.sh --version)"
  [[ "$keycloak_version" == *"26.7."* ]] || die "Expected Keycloak 26.7.x, found $keycloak_version"

  database_result="$(compose exec -T postgres psql --username=postgres --dbname=postgres --tuples-only --no-align --command="
    SELECT concat_ws(':',
      has_database_privilege('videogame_app', 'videogame_platform', 'CONNECT'),
      has_database_privilege('videogame_app', 'videogame_keycloak', 'CONNECT'),
      has_database_privilege('videogame_app_migrator', 'videogame_platform', 'CONNECT'),
      has_database_privilege('videogame_app_migrator', 'videogame_keycloak', 'CONNECT'),
      has_database_privilege('videogame_keycloak', 'videogame_keycloak', 'CONNECT'),
      has_database_privilege('videogame_keycloak', 'videogame_platform', 'CONNECT'),
      (SELECT NOT rolsuper AND NOT rolcreatedb AND NOT rolcreaterole FROM pg_roles WHERE rolname = 'videogame_app'),
      (SELECT NOT rolsuper AND NOT rolcreatedb AND NOT rolcreaterole FROM pg_roles WHERE rolname = 'videogame_app_migrator'),
      (SELECT NOT rolsuper AND NOT rolcreatedb AND NOT rolcreaterole FROM pg_roles WHERE rolname = 'videogame_keycloak'),
      NOT has_schema_privilege('videogame_app', 'public', 'CREATE'),
      (SELECT pg_get_userbyid(datdba) = 'videogame_app_migrator' FROM pg_database WHERE datname = 'videogame_platform'),
      (SELECT pg_get_userbyid(datdba) = 'videogame_keycloak' FROM pg_database WHERE datname = 'videogame_keycloak')
    );
  ")"
  [[ "$database_result" == "t:f:t:f:t:f:t:t:t:t:t:t" ]] \
    || die "Database role isolation or ownership check failed: $database_result"

  keycloak_hostname="$(env_value KEYCLOAK_HOSTNAME)"
  require_command curl
  curl --fail --silent --show-error \
    "$keycloak_hostname/realms/videogame-platform/.well-known/openid-configuration" \
    >/dev/null

  authorization_status="$(curl --silent --output /dev/null --write-out '%{http_code}' \
    --get "$keycloak_hostname/realms/videogame-platform/protocol/openid-connect/auth" \
    --data-urlencode 'client_id=videogame-platform-bff' \
    --data-urlencode 'redirect_uri=http://localhost:8080/login/oauth2/code/keycloak' \
    --data-urlencode 'response_type=code' \
    --data-urlencode 'scope=openid' \
    --data-urlencode 'code_challenge=0123456789012345678901234567890123456789012' \
    --data-urlencode 'code_challenge_method=S256')"
  [[ "$authorization_status" == "200" || "$authorization_status" == "302" ]] \
    || die "The imported BFF client rejected a valid authorization request (HTTP $authorization_status)"

  ci_authorization_status="$(curl --silent --output /dev/null --write-out '%{http_code}' \
    --get "$keycloak_hostname/realms/videogame-platform/protocol/openid-connect/auth" \
    --data-urlencode 'client_id=videogame-platform-bff' \
    --data-urlencode 'redirect_uri=http://application:8080/login/oauth2/code/keycloak' \
    --data-urlencode 'response_type=code' \
    --data-urlencode 'scope=openid' \
    --data-urlencode 'code_challenge=0123456789012345678901234567890123456789012' \
    --data-urlencode 'code_challenge_method=S256')"
  [[ "$ci_authorization_status" == "200" || "$ci_authorization_status" == "302" ]] \
    || die "The imported BFF client rejected the exact CI callback (HTTP $ci_authorization_status)"

  invalid_redirect_status="$(curl --silent --output /dev/null --write-out '%{http_code}' \
    --get "$keycloak_hostname/realms/videogame-platform/protocol/openid-connect/auth" \
    --data-urlencode 'client_id=videogame-platform-bff' \
    --data-urlencode 'redirect_uri=https://attacker.example/callback' \
    --data-urlencode 'response_type=code' \
    --data-urlencode 'scope=openid' \
    --data-urlencode 'code_challenge=0123456789012345678901234567890123456789012' \
    --data-urlencode 'code_challenge_method=S256')"
  [[ "$invalid_redirect_status" == "400" ]] \
    || die "The imported BFF client accepted an unlisted callback (HTTP $invalid_redirect_status)"

  identity_result="$(compose exec -T postgres psql --username=postgres --dbname=videogame_keycloak \
    --tuples-only --no-align --variable="local_user=$(env_value LOCAL_TEST_USER_USERNAME)" <<'SQL'
      SELECT concat_ws(':',
        (SELECT count(*) = 1 FROM realm WHERE name = 'videogame-platform'),
        (SELECT count(*) = 1
           FROM client c
           JOIN realm r ON r.id = c.realm_id
          WHERE r.name = 'videogame-platform'
            AND c.client_id = 'videogame-platform-bff'
            AND c.enabled
            AND NOT c.public_client
            AND c.client_authenticator_type = 'client-secret'
            AND c.standard_flow_enabled
            AND NOT c.implicit_flow_enabled
            AND NOT c.direct_access_grants_enabled
            AND NOT c.service_accounts_enabled
            AND c.secret IS NOT NULL),
        (SELECT count(*) = 1
           FROM client_attributes ca
           JOIN client c ON c.id = ca.client_id
           JOIN realm r ON r.id = c.realm_id
          WHERE r.name = 'videogame-platform'
            AND c.client_id = 'videogame-platform-bff'
            AND ca.name = 'pkce.code.challenge.method'
            AND ca.value = 'S256'),
        (SELECT count(*) = 1
           FROM user_entity u
           JOIN realm r ON r.id = u.realm_id
          WHERE r.name = 'videogame-platform'
            AND u.username = :'local_user'),
        (SELECT count(*) = 1
           FROM credential cr
           JOIN user_entity u ON u.id = cr.user_id
           JOIN realm r ON r.id = u.realm_id
          WHERE r.name = 'videogame-platform'
            AND u.username = :'local_user'
            AND cr.type = 'password')
      );
SQL
  )"
  [[ "$identity_result" == "t:t:t:t:t" ]] \
    || die "Realm, confidential client, PKCE or local-user verification failed: $identity_result"

  # The realm import runs only against an empty database, so a regenerated .env leaves the
  # persisted client secret behind and every code-to-token exchange fails as a cancelled login.
  # Compare through psql variables so the secret never appears in a command line or output.
  secret_matches="$(printf '%s\n' "SELECT count(*) = 1 FROM client c JOIN realm r ON r.id = c.realm_id WHERE r.name = 'videogame-platform' AND c.client_id = 'videogame-platform-bff' AND c.secret = :'expected';" \
    | compose exec -T postgres psql --username=postgres --dbname=videogame_keycloak \
        --tuples-only --no-align --variable="expected=$(env_value KEYCLOAK_BFF_CLIENT_SECRET)")"
  [[ "$secret_matches" == "t" ]] \
    || die "The persisted BFF client secret differs from KEYCLOAK_BFF_CLIENT_SECRET in .env; the realm was imported with an earlier value. Run the reset command and start again, or align the stored client secret."

  printf 'Runtime verification passed: PostgreSQL %s, Keycloak 26.7.x, health, database isolation, realm, confidential PKCE client and local user.\n' "$postgres_version"
}

command_name="${1:-}"
if (($#)); then shift; fi
for option in "$@"; do
  case "$command_name:$option" in
    up:--observability | application:--observability)
      [[ "$with_observability" == false ]] || die "Duplicate --observability"
      with_observability=true ;;
    up:--localization | application:--localization)
      [[ "$with_localization" == false ]] || die "Duplicate --localization"
      with_localization=true ;;
    reset:--yes)
      [[ "$reset_confirmed" == false ]] || die "Duplicate --yes"
      reset_confirmed=true ;;
    observability:--recreate)
      [[ "$recreate_observability" == false ]] || die "Duplicate --recreate"
      recreate_observability=true ;;
    *) die "Unsupported arguments; use up/application --observability --localization, observability --recreate or reset --yes" ;;
  esac
done

case "$command_name" in
  up)
    ensure_compose_available
    create_env_if_missing
    require_env
    create_backend_env_if_missing
    localization_wait_options=()
    if [[ "$with_localization" == true ]]; then
      require_local_model
      compose build catalogue-localizer
      localization_wait_options+=(--wait-timeout 600)
    fi
    if [[ "$with_observability" == true ]]; then prepare_local_metrics_secret; fi
    compose config --quiet
    compose up --detach --wait "${localization_wait_options[@]}"
    printf 'PostgreSQL is available on 127.0.0.1:%s.\n' "$(env_value POSTGRES_PORT)"
    printf 'Keycloak is available at %s.\n' "$(env_value KEYCLOAK_HOSTNAME)"
    ;;
  application)
    ensure_compose_available
    create_env_if_missing
    require_env
    create_backend_env_if_missing
    if [[ "$with_localization" == true ]]; then require_local_model; fi
    if [[ "$with_observability" == true ]]; then prepare_local_metrics_secret; fi
    compose --profile full up --build
    ;;
  observability)
    ensure_compose_available
    create_env_if_missing
    require_env
    create_backend_env_if_missing
    prepare_local_metrics_secret
    with_observability=true
    observability_options=()
    if [[ "$recreate_observability" == true ]]; then
      observability_options+=(--no-deps --force-recreate)
    fi
    compose up --detach "${observability_options[@]}" telemetry prometheus grafana alloy loki
    printf 'Grafana: http://127.0.0.1:3000; user: owner; password file: .local-secrets/grafana-admin-password\n'
    ;;
  verify-observability)
    ensure_compose_available
    require_env
    with_observability=true
    metrics_config="$(mktemp)"
    trap 'rm -f -- "$metrics_config"' EXIT
    compose --profile full config --format json >"$metrics_config"
    APPLICATION_VERSION="$(backend_reactor_version)" \
      python3 "$repository_root/scripts/private-dev-metrics-check.py" \
        --local --env-file "$env_file" --config "$metrics_config"
    ;;
  localization)
    ensure_compose_available
    create_env_if_missing
    require_env
    create_backend_env_if_missing
    require_local_model
    with_localization=true
    compose up --build --detach --wait --wait-timeout 120 catalogue-localizer
    printf 'Catalogue translation helper: http://127.0.0.1:8092; host backend endpoint uses loopback.\n'
    ;;
  verify-localization)
    ensure_compose_available
    require_env
    with_localization=true
    compose exec -T catalogue-localizer python -c \
      'import urllib.request; urllib.request.urlopen("http://127.0.0.1:8092/ready", timeout=2).close(); print("Catalogue translation model/helper ready.")'
    ;;
  down)
    with_observability=true
    with_localization=true
    ensure_compose_available
    require_env
    compose down --remove-orphans
    ;;
  status)
    with_observability=true
    with_localization=true
    ensure_compose_available
    require_env
    compose ps
    ;;
  logs)
    ensure_compose_available
    require_env
    compose logs --follow postgres keycloak
    ;;
  verify)
    ensure_compose_available
    require_env
    verify_runtime
    ;;
  verify-images)
    ensure_compose_available
    docker buildx version >/dev/null 2>&1 || die "Docker Buildx is required to inspect OCI manifests"
    verify_image_platform "$postgres_image"
    verify_image_platform "$keycloak_image"
    ;;
  reset)
    with_observability=true
    with_localization=true
    ensure_compose_available
    require_env
    if [[ "$reset_confirmed" == false ]]; then
      printf 'This deletes only containers and named volumes in Compose project %s.\n' "$(env_value COMPOSE_PROJECT_NAME)"
      read -r -p 'Delete disposable local PostgreSQL, Keycloak, metrics and logs data? [y/N] ' confirmation
      [[ "$confirmation" == "y" || "$confirmation" == "Y" ]] || die "Reset cancelled"
    fi
    compose down --volumes --remove-orphans
    printf 'Deleted disposable Compose data. The ignored environment files were preserved.\n'
    ;;
  *)
    usage
    [[ -n "$command_name" ]] && exit 1
    ;;
esac
