apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: videogame-platform-dev
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd-image-updater.argoproj.io/image-list: game-service=ghcr.io/rubhern/videogame-platform/game-service
    argocd-image-updater.argoproj.io/update-strategy.game-service: digest
    argocd-image-updater.argoproj.io/write-back-method: git
spec:
  project: default
  source:
    repoURL: https://github.com/rubhern/videogame-platform.git
    targetRevision: main
    path: infra/dev/videogame-platform
    helm: {}
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true