# ─────────────────────
# Spring configuration
# ─────────────────────
spring:
  application:
    name: game
  # SQL initialization (schema + data scripts)
  sql:
    init:
      mode: always
      schema-locations: classpath:sql/schema.sql
      data-locations: classpath:sql/data.sql

  datasource:
    url: jdbc:postgresql://172.22.233.21:30050/gamedb
    driver-class-name: org.postgresql.Driver
    username: user
    password: pass

  jpa:
    hibernate:
      ddl-auto: none          # keep schema managed by scripts
    show-sql: true            # show SQL in logs (dev only)

# ─────────────────────
# Server configuration
# ─────────────────────
server:
  port: 8090

# ─────────────────────
# Health check & Actuator
# ─────────────────────
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  health:
    db:
      enabled: true
    diskspace:
      enabled: true
    ping:
      enabled: true
  info:
    env:
      enabled: true

# ─────────────────────
# Application info
# ─────────────────────
info:
  app:
    environment: production

# ─────────────────────
# OpenAPI / Swagger UI
# ─────────────────────
springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    url: /openapi/game-api.yaml
