apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "game-service.fullname" . }}-actuator
  annotations:
    konghq.com/plugins: ""
spec:
  ingressClassName: kong
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /actuator(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: {{ include "game-service.fullname" . }}
                port:
                  number: {{ .Values.service.port }}
