apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: auth-oidc
plugin: kong-openid-connect
config:
  discovery: "http://keycloak.keycloak.svc.cluster.local/realms/videogame-platform/.well-known/openid-configuration"
  client_id: "vgp-api-services"
  client_secret: "YKc1969cJb0BJ9IkbPXO7QGhheEhYTUT"
  bearer_only: true
  introspection_endpoint_auth_method: "client_secret_basic"
  introspection_endpoint: "http://keycloak.keycloak.svc.cluster.local/realms/videogame-platform/protocol/openid-connect/token/introspect"
