apiVersion: 1
prune: true
datasources:
  - name: Platform metrics
    uid: private-dev-prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false
    jsonData:
      httpMethod: POST
      timeInterval: 60s
      queryTimeout: 15s
