name: ci

############################################################
# 1 ▸ Triggers
############################################################
on:
  push:
    branches: [main]
    paths: ['services/**']
  pull_request:
    branches: [main]
  workflow_dispatch:
  schedule:
    - cron: '2 10 * * *'

############################################################
# 2 ▸ Permissions and policy
############################################################
permissions:
  contents: read
  packages: write
  id-token: write

defaults:
  run:
    shell: bash

############################################################
# 3 ▸ Job “build”
############################################################
jobs:
  build:
    runs-on: ubuntu-latest
    concurrency:
      group: ci-${{ github.ref }}-${{ matrix.service }}
      cancel-in-progress: true

    strategy:
      matrix:
        service:
          - game-service

    env:
      REGISTRY: ghcr.io
      IMAGE_PREFIX: ${{ github.repository }}
      MAVEN_OPTS: >-
        -Dmaven.repo.local=$HOME/.m2/repository
        -Dmaven.artifact.threads=8
        -Dorg.slf4j.simpleLogger.showDateTime=true

    steps:
      #-------------------------------------------------------
      # 3.1 Checkout & cachés
      #-------------------------------------------------------
      - name: 📥 Checkout
        uses: actions/checkout@v4
        with: {fetch-depth: 0}

      - name: 💾 Cache Maven
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            m2-

      - name: 🏗️ Set up Temurin 21
        uses: actions/setup-java@v4
        with: {distribution: temurin, java-version: 21}

      #-------------------------------------------------------
      # 3.2 Build + Unit Tests
      #-------------------------------------------------------
      - name: 🧪 Build & verify
        run: mvn -f services/${{ matrix.service }}/pom.xml --batch-mode verify -Dmaven.test.failure.ignore=false

      #-------------------------------------------------------
      # 3.3 Sonar + Quality Gate
      #-------------------------------------------------------
      - name: 🔎 SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v2
        with:
          projectBaseDir: services/${{ matrix.service }}
          args: >
            -Dsonar.projectKey=videogame-platform-${{ matrix.service }}
            -Dsonar.tests=src/test/java
            -Dsonar.coverage.exclusions=**/*Test.java,**/*IT.java
        env:
          SONAR_TOKEN:    ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ vars.SONAR_HOST_URL }}

      - name: ✅ SonarQube Quality Gate
        uses: SonarSource/sonarqube-quality-gate-action@v1
        with:
          scanMetadataReportFile: services/${{ matrix.service }}/.scannerwork/report-task.txt
        env:
          SONAR_TOKEN:    ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ vars.SONAR_HOST_URL }}

      #-------------------------------------------------------
      # 3.4 Container build, push, SBOM, firma
      #-------------------------------------------------------
      - name: 🐳 Set up Buildx
        uses: docker/setup-buildx-action@v3.10.0
        with: {version: latest}

      - name: 🔐 Login GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 📦 Build & push image
        id: buildx
        uses: docker/build-push-action@v6
        with:
          context: services/${{ matrix.service }}
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_PREFIX }}/${{ matrix.service }}:${{ github.sha }}
            ${{ env.REGISTRY }}/${{ env.IMAGE_PREFIX }}/${{ matrix.service }}:latest
          labels: |
            org.opencontainers.image.source=${{ github.server_url }}/${{ github.repository }}

      - name: 🏷️  Export IMAGE_REF
        run: | 
          echo "IMAGE_REF=${{ env.REGISTRY }}/${{ env.IMAGE_PREFIX }}/${{ matrix.service }}@${{ steps.buildx.outputs.digest }}" >> "$GITHUB_ENV"

      - name: 🔒 Cosign sign (keyless)
        uses: sigstore/cosign-installer@v3
      - run: cosign sign --yes ${{ env.IMAGE_REF }}
        env:
          COSIGN_EXPERIMENTAL: "true"

      - name: 🛡️ Trivy image scan
        uses: aquasecurity/trivy-action@0.31.0
        with:
          image-ref: ${{ env.REGISTRY }}/${{ env.IMAGE_PREFIX }}/${{ matrix.service }}:${{ github.sha }}
          severity: CRITICAL,HIGH